import typing

REMOTE_RESULTS_UNAVAILABLE = 83
NETWORK_TIMEOUT = 89
SHUTDOWN_IN_PROGRESS = 91
OPERATION_FAILED = 96
CONFIGURATION_IN_PROGRESS = 109
CONFLICTING_OPERATION_IN_PROGRESS = 117
POOLED_CONNECTIONS_DROPPED = 145
NETWORK_INTERFACE_EXCEEDED_TIME_LIMIT = 202
EXCEEDED_TIME_LIMIT = 262
NOT_MASTER = 10107
INTERRUPTED_AT_SHUTDOWN = 11600
INTERRUPTED = 11601
INTERRUPTED_DUE_TO_STEP_DOWN = 11602
NOT_MASTER_OR_SECONDARY = 13436
NOT_MASTER_NO_SLAVE_OK = 13435

DEFAULT_RETRY: typing.Set[int] = {
    REMOTE_RESULTS_UNAVAILABLE,
    NETWORK_TIMEOUT,
    SHUTDOWN_IN_PROGRESS,
    OPERATION_FAILED,
    CONFIGURATION_IN_PROGRESS,
    CONFLICTING_OPERATION_IN_PROGRESS,
    POOLED_CONNECTIONS_DROPPED,
    NETWORK_INTERFACE_EXCEEDED_TIME_LIMIT,
    EXCEEDED_TIME_LIMIT,
    NOT_MASTER,
    NOT_MASTER_NO_SLAVE_OK,
    NOT_MASTER_OR_SECONDARY,
    INTERRUPTED_AT_SHUTDOWN,
    INTERRUPTED,
    INTERRUPTED_DUE_TO_STEP_DOWN,
}
